### ISSUE TITLE
[`semester-upkeep`] Migrate `autobot` to a VPS

### ISSUE THREAD

**Issue by ionlights** [ucfai/bot#31]
Currently, `autobot` lives on the computers of @ionlights, @SirRoboto, and @brandons209 – this is less-than-ideal for obvious reasons (we don't have near-infinite up-time). To avoid this, we need to migrate `autobot` to a VPS.

## Tasks
- [ ] (`🔑 Required`) Iron out the dependencies that `autobot` needs to function flawlessly. Version-lock only what's required, in [`envs/linux.yml`](../blob/master/envs/linux.yml).
- [ ] (`🔑 Required`) Make sure that `pip install git+https://github.com/ucfai/bot@master` doesn't break `autobot`
   - This is mostly a pathing issue, as far as I'm aware. We can hardcode a path into something like `/ucfai` on machines that AI@UCF owns/maintains.
- [ ] (`🍜 Nice to Have`) [`scripts/setup`](../blob/master/scripts/setup) does a bang-up job creating a reproducible setup across Linux machines.
   - This could be converted from `bash` to `python`. (No arguments there.)
- [ ] (`🍜 Nice to Have`) Package up `autobot` into a `docker` container.
