### ISSUE TITLE
[`semester-upkeep`] Date and filename manipulation

### ISSUE THREAD

**Issue by ionlights** [ucfai/bot#32]
Dates are fun! 😂 Really, though, they're kind of a nuisance. We have a few weird things that can change throughout the semester, with respect to dates and room placement.

## Tasks
- [ ] (`🔑 Required`) Allow for dates specified in `syllabus.yml` to override any calculated dates from the `autobot.apis.ucf`.
- [ ] (`🔑 Required`) If the date follows the meeting pattern, as specified in [`overhead.yml`](../blob/master/autobot/templates/seed/group/overhead.yml), then automatically accept the new date – even if it leaves weeks of gaps.
- [ ] (`🔑 Required`) Meetings are unlikely to change (especially if the "rules" are followed – all meetings are specified at the beginning of the semester). However, there are often cases where we either need to resolve name changes or date changes.
   - Within a group's semester, **all filenames _must be unique_**, so this resolution becomes a wee easier. **Always trust the `syllabus.yml`'s data over what exists on disk.
- [ ] (`🍜 Nice to Have`) Allow for off-pattern meeting days.
- [ ] (`🍜 Nice to Have`) Adapt this for ops meetings as well. @SirRoboto thoughts on this?
