### ISSUE TITLE
[Total Automation] Check for merge compatibility and Kaggle eligibility

### ISSUE THREAD

**Issue by ionlights** [ucfai/bot#33]
Mostly needed for Kaggle Kernels, but can also be used for something like GitHub Actions.

## Tasks
- [ ] (`🔑 Required`) Evaluate notebook candidacy to be merged back into the group's repository
   - Check that the "non-solution" notebook can be generated without error.
   - Check that all other steps can be run without error (downloading papers, generating banners, compiling website pages, etc.)
- [ ] (`🔑 Required`) If the notebook is merged back into `master`, rebuild the website and propagate new changes.
- [ ] (`🔑 Required`) `diff` candidate notebook from the one on Kaggle
- [ ] (`🔑 Required`) Push most recent notebook to Kaggle 15 minutes before the meeting time
