### ISSUE TITLE
[Hugo Migration] Metadata generation and directory restructuring

### ISSUE THREAD

**Issue by ionlights** [ucfai/bot#35]
## Tasks
- [ ] (`🔑 Required`) Generate `authors` for `hugo-academic`
- [ ] (`🔑 Required`) Adjust `autobot's` compilation directory structure for `hugo-academic`
- [ ] (`🍜 Nice to Have`) Automatically update schedules for each group
- [ ] (`🍜 Nice to Have`) Automatically add/update coordinators (past/present) and tag their contributions to AI@UCF
- [ ] (`🍜 Nice to Have`) Setup "Documentation" structure for...
   - **Hackpack**
   - `autobot`
   - AI@UCF – @SirRoboto @ionlights
