### ISSUE TITLE
[Total Automation] Integrate "cascade" CI

### ISSUE THREAD

**Issue by ionlights** [ucfai/bot#37]
CI/CD is useful when trying to protect code-bases against breaking changes. We actually have two systems that need CI/CD.

1. `autobot` itself
1. each of the groups

## Tasks
- [] (`🔑 Required`) Before merging PRs, run unit-tests to validate the functionality of `autobot` before approving PRs
- [] (`🔑 Required`) Whenever one of the groups receives a PR, trigger a compilation build for that specific meeting
- [] (`🔑 Required`) Whenever a PR in a group is merged, trigger a compilation of the website and push the latest version of the notebook to Kaggle
- [] (`🔑 Required`) Whenever YouTube uploads finish, trigger another website build

**Comment by Haugf** [comment]
Hey John, we're thinking about adding a `tests/` folder under `autobot/`, can we go over making and testing these unit tests later?

**Comment by ionlights** [comment]
hmm, so... looking at [StackOverflow][stack] and at [`py.test`][py.test]...
it's kinda, "up to us" to organize the folders. personally, behind the idea of throwing all the tests into a mirrored directory structure that's separate from `autobot`'s source.

so... it would look something like this:
```
...
autobot
tests  <---
setup.py
...
```

[stack]: https://stackoverflow.com/a/62527
[py.test]: https://docs.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery

**Comment by Haugf** [comment]
pyTest has some self explanatory syntax  and it is also the default test package for git actions.

I think this is the better choice

**Comment by ionlights** [comment]
alright, sweet. try to keep track of edits/changes in the `conda` environment files in `envs/`?

**Comment by Haugf** [comment]
Are the conda environment files the linux and macos .yml files?

**Comment by ionlights** [comment]
> Are the conda environment files the linux and macos .yml files?

yep! ignore anything else in that folder, for now – i think the "requirements" that show up are for `conda` explicitly (since you can use `pip` there, but **please do so only as a last resort.**)

**Comment by ionlights** [comment]
https://github.com/ucfai/bot/blob/ebfca5e03b9c115b27ffc68b4635efa4f0da73bc/.github/workflows/docker.yml#L1

Building the environment in a Docker container that's released to:
- https://docker.pkg.github.com.com/ucfai/bot/env
- https://docker.pkg.github.com.com/ucfai/bot/development
- https://docker.pkg.github.com.com/ucfai/bot/production
