### ISSUE TITLE
Attendance Tracking/Reports

### ISSUE THREAD

**Issue by ionlights** [ucfai/bot#8]
- [x] Can we make use of UCFID to extract required info for data analysis to determine if we're meeting out demographic goals?
---
- [x] Execute a template Jupyter Notebook to generate a report
- [x] Dump said report to a PDF / HTML subsite to send to sponsors
- [x] Extract data for internal analysis as well
